# Generated by Django 3.2.13 on 2022-06-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joke', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Joke',
                'verbose_name_plural': 'Jokes',
            },
        ),
        migrations.DeleteModel(
            name='JokeAPI',
        ),
    ]
